package com.physphil.android.unitconverterultimate.models

enum class CurrencyCode(val value: String) {
    AUD(CurrencyCodes.AUD),
    BGN(CurrencyCodes.BGN),
    BRL(CurrencyCodes.BRL),
    CAD(CurrencyCodes.CAD),
    CHF(CurrencyCodes.CHF),
    CNY(CurrencyCodes.CNY),
    CZK(CurrencyCodes.CZK),
    DKK(CurrencyCodes.DKK),
    EUR(CurrencyCodes.EUR),
    GBP(CurrencyCodes.GBP),
    HKD(CurrencyCodes.HKD),
    HRK(CurrencyCodes.HRK),
    HUF(CurrencyCodes.HUF),
    IDR(CurrencyCodes.IDR),
    ILS(CurrencyCodes.ILS),
    INR(CurrencyCodes.INR),
    ISK(CurrencyCodes.ISK),
    JPY(CurrencyCodes.JPY),
    KRW(CurrencyCodes.KRW),
    MXN(CurrencyCodes.MXN),
    MYR(CurrencyCodes.MYR),
    NOK(CurrencyCodes.NOK),
    NZD(CurrencyCodes.NZD),
    PHP(CurrencyCodes.PHP),
    PLN(CurrencyCodes.PLN),
    RON(CurrencyCodes.RON),
    RUB(CurrencyCodes.RUB),
    SEK(CurrencyCodes.SEK),
    SGD(CurrencyCodes.SGD),
    THB(CurrencyCodes.THB),
    TRY(CurrencyCodes.TRY),
    USD(CurrencyCodes.USD),
    ZAR(CurrencyCodes.ZAR)
}